name: checktimekeeping
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  camera: ^0.11.2

  tflite_flutter: ^0.11.0
  google_mlkit_face_detection: ^0.10.0
  image: ^4.1.3


  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.3
  firebase_auth: ^5.3.1
  
  permission_handler: ^11.3.1


  cloudinary_public: ^0.23.1
  http: ^1.2.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/models/mobilefacenet.tflite
